from sqlalchemy import Column, Integer, BigInteger, String, DateTime, Text, Float, Date
from sqlalchemy.dialects.mysql import DOUBLE, DECIMAL, TEXT, MEDIUMTEXT, MEDIUMBLOB, TINYINT, LONGTEXT, BINARY, SMALLINT, MEDIUMINT, BIT, TIMESTAMP, TIME
from sqlalchemy import MetaData, Table

metadata = MetaData()

predictive_twins_archive = Table('predictive_twins_archive', metadata, 

    Column('Forecast_Generation_Date', DateTime, primary_key=False, autoincrement=False),
    Column('Forecast_Start_Date', Date, primary_key=True, autoincrement=False),
    Column('MDS', String(255), primary_key=False, autoincrement=False),
    Column('Serial_Number', String(255), primary_key=True, autoincrement=False),
    Column('MAJCOM', String(255), primary_key=False, autoincrement=False),
    Column('Owner', String(255), primary_key=False, autoincrement=False),
    Column('Owner_Loc_Code', String(255), primary_key=False, autoincrement=False),
    Column('At_Depot', TINYINT, primary_key=False, autoincrement=False),
    Column('Current_Airframe_Hours_Since_2004', Float, primary_key=False, autoincrement=False),
    Column('Last_Sortie_Date', DateTime, primary_key=False, autoincrement=False),
    Column('Work_Unit_Code', String(255), primary_key=True, autoincrement=False),
    Column('Position', String(255), primary_key=True, autoincrement=False),
    Column('Eta', Float, primary_key=False, autoincrement=False),
    Column('Beta', Float, primary_key=False, autoincrement=False),
    Column('Hours_Threshold', Float, primary_key=False, autoincrement=False),
    Column('Hours_Threshold_CDF_Equivalent', Float, primary_key=False, autoincrement=False),
    Column('CDF_Threshold', Float, primary_key=False, autoincrement=False),
    Column('CDF_Threshold_Hours_Equivalent', Float, primary_key=False, autoincrement=False),
    Column('Last_Install_Date', Date, primary_key=False, autoincrement=False),
    Column('Last_Install_Airframe_Hours_Since_2004', Float, primary_key=False, autoincrement=False),
    Column('Lost_Position', TINYINT, primary_key=False, autoincrement=False),
    Column('Current_TOW', Float, primary_key=False, autoincrement=False),
    Column('CDF_Value', Float, primary_key=False, autoincrement=False),
    Column('Hours_Until_Threshold', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_Now', TINYINT, primary_key=False, autoincrement=False),
    Column('Optempo_Now_to_1_Month', Float, primary_key=False, autoincrement=False),
    Column('TOW_Plus_1_Month', Float, primary_key=False, autoincrement=False),
    Column('CDF_Plus_1_Month', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_Now_to_1_Month', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_Now_to_1_Month', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_Up_to_1_Month', Float, primary_key=False, autoincrement=False),
    Column('Optempo_1_to_2_Months', Float, primary_key=False, autoincrement=False),
    Column('TOW_Plus_2_Months', Float, primary_key=False, autoincrement=False),
    Column('CDF_Plus_2_Months', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_1_to_2_Months', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_1_to_2_Months', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_Now_to_2_Months', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_Up_to_2_Months', Float, primary_key=False, autoincrement=False),
    Column('Optempo_2_to_3_Months', Float, primary_key=False, autoincrement=False),
    Column('TOW_Plus_3_Months', Float, primary_key=False, autoincrement=False),
    Column('CDF_Plus_3_Months', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_2_to_3_Months', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_2_to_3_Months', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_Now_to_3_Months', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_Up_to_3_Months', Float, primary_key=False, autoincrement=False),
    Column('Optempo_3_to_4_Months', Float, primary_key=False, autoincrement=False),
    Column('TOW_Plus_4_Months', Float, primary_key=False, autoincrement=False),
    Column('CDF_Plus_4_Months', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_3_to_4_Months', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_3_to_4_Months', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_Now_to_4_Months', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_Up_to_4_Months', Float, primary_key=False, autoincrement=False),
    Column('Optempo_4_to_5_Months', Float, primary_key=False, autoincrement=False),
    Column('TOW_Plus_5_Months', Float, primary_key=False, autoincrement=False),
    Column('CDF_Plus_5_Months', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_4_to_5_Months', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_4_to_5_Months', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_Now_to_5_Months', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_Up_to_5_Months', Float, primary_key=False, autoincrement=False),
    Column('Optempo_5_to_6_Months', Float, primary_key=False, autoincrement=False),
    Column('TOW_Plus_6_Months', Float, primary_key=False, autoincrement=False),
    Column('CDF_Plus_6_Months', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_5_to_6_Months', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_5_to_6_Months', Float, primary_key=False, autoincrement=False),
    Column('Pr_Rmvl_Now_to_6_Months', Float, primary_key=False, autoincrement=False),
    Column('Threshold_Crossed_Up_to_6_Months', Float, primary_key=False, autoincrement=False),
    Column('__id__', String(255), primary_key=True, autoincrement=False),
)