from sqlalchemy import Column, Integer, BigInteger, String, DateTime, Text, Float, Date
from sqlalchemy.dialects.mysql import DOUBLE, DECIMAL, TEXT, MEDIUMTEXT, MEDIUMBLOB, TINYINT, LONGTEXT, BINARY, SMALLINT, MEDIUMINT, BIT, TIMESTAMP, TIME
from sqlalchemy import MetaData, Table

metadata = MetaData()

compiled_remis_data = Table('compiled_remis_data', metadata, 

    Column('Import_Date', Date, primary_key=False, autoincrement=False),
    Column('Record_Type', String(255), primary_key=False, autoincrement=False),
    Column('Equipment_Designator', String(255), primary_key=False, autoincrement=False),
    Column('Type_Equipment', String(255), primary_key=False, autoincrement=False),
    Column('Block_Number', Integer, primary_key=False, autoincrement=False),
    Column('Standard_Reporting_Designator', String(255), primary_key=False, autoincrement=False),
    Column('Federal_Supply_Classification', Integer, primary_key=False, autoincrement=False),
    Column('Serial_Number', String(255), primary_key=False, autoincrement=False),
    Column('Current_Operating_Time', Float, primary_key=False, autoincrement=False),
    Column('Job_Control_Number', String(255), primary_key=False, autoincrement=False),
    Column('Command', String(255), primary_key=False, autoincrement=False),
    Column('Geographic_Location', String(255), primary_key=False, autoincrement=False),
    Column('Organization', String(255), primary_key=False, autoincrement=False),
    Column('TCTO_Data_Code', String(255), primary_key=False, autoincrement=False),
    Column('Work_Unit_Code', String(255), primary_key=False, autoincrement=False),
    Column('Component_Part_Number', String(255), primary_key=False, autoincrement=False),
    Column('Component_Serial_Number', String(255), primary_key=False, autoincrement=False),
    Column('Component_Position_Number', Integer, primary_key=False, autoincrement=False),
    Column('Type_Maintenance_Code', String(255), primary_key=False, autoincrement=False),
    Column('Action_Taken_Code', String(255), primary_key=False, autoincrement=False),
    Column('When_Discovered_Code', String(255), primary_key=False, autoincrement=False),
    Column('How_Malfunction_Code', Integer, primary_key=False, autoincrement=False),
    Column('How_Malfunction_Class_Ind', Integer, primary_key=False, autoincrement=False),
    Column('AFTO_Form_350_Tag_Number', Integer, primary_key=False, autoincrement=False),
    Column('Posting_Date', Date, primary_key=False, autoincrement=False),
    Column('Work_Order_Number', BigInteger, primary_key=True, autoincrement=False),
    Column('Work_Center_Event_Identifier', Integer, primary_key=True, autoincrement=False),
    Column('Sequence_Number', Integer, primary_key=True, autoincrement=False),
    Column('Transaction_Date', Date, primary_key=False, autoincrement=False),
    Column('Start_Time', Integer, primary_key=False, autoincrement=False),
    Column('Stop_Time', Integer, primary_key=False, autoincrement=False),
    Column('Performing_Geographic_Location', String(255), primary_key=False, autoincrement=False),
    Column('Work_Center_Code', String(255), primary_key=False, autoincrement=False),
    Column('Crew_Size', Integer, primary_key=False, autoincrement=False),
    Column('Units', Integer, primary_key=False, autoincrement=False),
    Column('Labor_Manhours', Float, primary_key=False, autoincrement=False),
    Column('On_Base_Turn_In_Doc_Number', String(255), primary_key=False, autoincrement=False),
    Column('On_Equip_Work_Center_Event_Id', Integer, primary_key=False, autoincrement=False),
    Column('On_Equip_Sequence_Number', Integer, primary_key=False, autoincrement=False),
    Column('Activity_Identifier', String(255), primary_key=False, autoincrement=False),
    Column('Maintenance_Priority', String(255), primary_key=False, autoincrement=False),
    Column('Maintainer_Name', String(255), primary_key=False, autoincrement=False),
    Column('Documenter_Name', String(255), primary_key=False, autoincrement=False),
    Column('Installed_Equipment_Designator', String(255), primary_key=False, autoincrement=False),
    Column('Installed_Serial_Number', String(255), primary_key=False, autoincrement=False),
    Column('Installed_CAGE_Code', String(255), primary_key=False, autoincrement=False),
    Column('Installed_Lot_Number', String(255), primary_key=False, autoincrement=False),
    Column('Installed_Type_Equipment', String(255), primary_key=False, autoincrement=False),
    Column('Installed_Work_Unit_Code', String(255), primary_key=False, autoincrement=False),
    Column('Installed_Location_Identifier', String(255), primary_key=False, autoincrement=False),
    Column('Installed_Current_Operating_Time', Float, primary_key=False, autoincrement=False),
    Column('Installed_Prev_Operating_Time', Float, primary_key=False, autoincrement=False),
    Column('Removed_Equipment_Designator', String(255), primary_key=False, autoincrement=False),
    Column('Removed_Serial_Number', String(255), primary_key=False, autoincrement=False),
    Column('Removed_CAGE_Code', String(255), primary_key=False, autoincrement=False),
    Column('Removed_Lot_Number', String(255), primary_key=False, autoincrement=False),
    Column('Removed_Type_Equipment', String(255), primary_key=False, autoincrement=False),
    Column('Removed_Work_Unit_Code', String(255), primary_key=False, autoincrement=False),
    Column('Removed_Location_Identifier', String(255), primary_key=False, autoincrement=False),
    Column('Removed_Current_Operating_Time', Float, primary_key=False, autoincrement=False),
    Column('Removed_Prev_Operating_Time', Float, primary_key=False, autoincrement=False),
    Column('Installed_EI_Equip_Designator', String(255), primary_key=False, autoincrement=False),
    Column('Installed_EI_Serial_Number', String(255), primary_key=False, autoincrement=False),
    Column('Installed_EI_SRD', String(255), primary_key=False, autoincrement=False),
    Column('Installed_EI_Type_Equipment', String(255), primary_key=False, autoincrement=False),
    Column('Installed_EI_Work_Unit_Code', String(255), primary_key=False, autoincrement=False),
    Column('Installed_EI_Comp_Part_Number', String(255), primary_key=False, autoincrement=False),
    Column('Installed_EI_Comp_Serial_Number', String(255), primary_key=False, autoincrement=False),
    Column('Discrepancy_Narrative', LONGTEXT, primary_key=False, autoincrement=False),
    Column('Work_Center_Event_Narrative', LONGTEXT, primary_key=False, autoincrement=False),
    Column('Corrective_Narrative', LONGTEXT, primary_key=False, autoincrement=False),
    Column('WUC_Narrative', LONGTEXT, primary_key=False, autoincrement=False),
    Column('Installed_EI_WUC_Narrative', LONGTEXT, primary_key=False, autoincrement=False),
    Column('Installed_WUC_Narrative', LONGTEXT, primary_key=False, autoincrement=False),
    Column('Removed_WUC_Narrative', LONGTEXT, primary_key=False, autoincrement=False),
    Column('__id__', String(255), primary_key=True, autoincrement=False),
)