from sqlalchemy import Column, Integer, BigInteger, String, DateTime, Text, Float, Date
from sqlalchemy.dialects.mysql import LONGTEXT, BIGINT
from sqlalchemy import MetaData, Table

metadata = MetaData()

on_equipment_maintenance = Table('on_equipment_maintenance', metadata,

    Column('File_Name', String(255)),
    Column('On_Work_Order_Key', Integer),
    Column('On_Maint_Action_Key', Integer, primary_key=True, autoincrement=False),
    Column('Record_Identifier', Integer),
    Column('Record_Type', String(12)),
    Column('Equipment_Designator', String(12)),
    Column('Type_Equipment', String(1)),
    Column('Block_Number', Integer),
    Column('Standard_Reporting_Designator', String(3)),
    Column('Serial_Number', String(45)),
    Column('Current_Operating_Time', Float),
    Column('Job_Control_Number', String(9)),
    Column('Command', String(3)),
    Column('Geographic_Location', String(4)),
    Column('Organization', String(45)),
    Column('TCTO_Data_Code', String(12)),
    Column('Discrepancy_Narrative', LONGTEXT),
    Column('Work_Unit_Code', String(45)),
    Column('On_Component_Part_Number', String(45)),
    Column('On_Component_Serial_Number', String(45)),
    Column('Component_Position_Number', Integer),
    Column('Type_Maintenance_Code', String(1)),
    Column('Action_Taken_Code', String(6)),
    Column('When_Discovered_Code', String(3)),
    Column('How_Malfunction_Code', Integer),
    Column('How_Malfunction_Class_Ind', Integer),
    Column('AFTO_Form_350_Tag_Number', Integer),
    Column('Work_Center_Event_Identifier', Integer, primary_key=True, autoincrement=False),
    Column('Sequence_Number', BIGINT, primary_key=True, autoincrement=False),
    Column('Transaction_Date', Date),
    Column('Start_Time', Integer),
    Column('Stop_Time', Integer),
    Column('Performing_Geographic_Location', String(4)),
    Column('Work_Center_Code', String(12)),
    Column('Crew_Size', Integer),
    Column('Units', Integer),
    Column('Labor_Manhours', Float),
    Column('Activity_Identifier', String(12)),
    Column('Maintenance_Priority', String(12)),
    Column('WUC_Narrative', LONGTEXT),
    Column('Maintainer_Name', String(45)),
    Column('Documenter_Name', String(45)),
    Column('Install_EI_Equip_Designator', String(45)),
    Column('Install_EI_Serial_Number', String(45)),
    Column('Install_EI_SRD', String(3)),
    Column('Install_EI_Type_Equipment', String(1)),
    Column('Install_EI_Work_Unit_Code', String(45)),
    Column('Install_EI_Comp_Part_Number', String(45)),
    Column('Install_EI_Comp_Serial_Number', String(45)),
    Column('Install_EI_WUC_Narrative', LONGTEXT),
    Column('Install_Equipment_Designator', String(45)),
    Column('Install_Serial_Number', String(45)),
    Column('Install_CAGE_Code', String(12)),
    Column('Install_Lot_Number', String(15)),
    Column('Install_Type_Equipment', String(1)),
    Column('Install_Work_Unit_Code', String(12)),
    Column('Install_Location_Identifier', String(12)),
    Column('Install_Current_Operating_Time', Float),
    Column('Install_Prev_Operating_Time', Float),
    Column('Install_WUC_Narrative', LONGTEXT),
    Column('Remove_Equipment_Designator', String(45)),
    Column('Remove_Serial_Number', String(45)),
    Column('Remove_CAGE_Code', String(12)),
    Column('Remove_Lot_Number', String(15)),
    Column('Remove_Type_Equipment', String(1)),
    Column('Remove_Work_Unit_Code', String(42)),
    Column('Remove_Location_Identifier', String(12)),
    Column('Remove_Current_Operating_Time', Float),
    Column('Remove_Prev_Operating_Time', Float),
    Column('Remove_WUC_Narrative', LONGTEXT),
    Column('Work_Center_Event_Narrative', LONGTEXT),
    Column('Corrective_Narrative', LONGTEXT),
    Column('Off_Maint_Action_Key', Integer, primary_key=True, autoincrement=False),
    Column('Work_Order_Number', BIGINT, primary_key=True, autoincrement=False),
    Column('Federal_Supply_Classification', Integer),
    Column('Off_Component_Part_Number', String(45)),
    Column('Off_Component_Serial_Number', String(45)),
    Column('On_Base_Turn_In_Doc_Number', String(45)),
    Column('On_Equip_Work_Center_Event_Id', Integer),
    Column('On_Equip_Sequence_Number', Integer),
    Column('Depot_Maint_Action_Key', Integer, primary_key=True, autoincrement=False),
    Column('Column_for_Asterisks', Integer),
    Column('Off_Work_Order_Key', Integer),
    Column('Depot_Work_Order_Key', Integer)
    )